//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.LdapServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", ConfigurationName="LdapServiceRef.LdapService")]
    public interface LdapService {
        
        // CODEGEN: Generating message contract since the wrapper name (ldapMessageResponse) of message ldapAuthResponse does not match the default value (ldapAuth)
        [System.ServiceModel.OperationContractAttribute(Action="http://wcss.keysight.com/EnterpriseBroker/LdapAuth#ldapAuth", ReplyAction="*")]
        ConsoleApplication1.LdapServiceRef.ldapAuthResponse ldapAuth(ConsoleApplication1.LdapServiceRef.ldapAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcss.keysight.com/EnterpriseBroker/LdapAuth#ldapAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.LdapServiceRef.ldapAuthResponse> ldapAuthAsync(ConsoleApplication1.LdapServiceRef.ldapAuthRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ldapAuth", WrapperNamespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", IsWrapped=true)]
    public partial class ldapAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", Order=0)]
        public string Application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", Order=1)]
        public string IdType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", Order=2)]
        public string Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", Order=3)]
        public string Password;
        
        public ldapAuthRequest() {
        }
        
        public ldapAuthRequest(string Application, string IdType, string Id, string Password) {
            this.Application = Application;
            this.IdType = IdType;
            this.Id = Id;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ldapMessageResponse", WrapperNamespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", IsWrapped=true)]
    public partial class ldapAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", Order=0)]
        public string LdapMessage;
        
        public ldapAuthResponse() {
        }
        
        public ldapAuthResponse(string LdapMessage) {
            this.LdapMessage = LdapMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LdapServiceChannel : ConsoleApplication1.LdapServiceRef.LdapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LdapServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.LdapServiceRef.LdapService>, ConsoleApplication1.LdapServiceRef.LdapService {
        
        public LdapServiceClient() {
        }
        
        public LdapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LdapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LdapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.LdapServiceRef.ldapAuthResponse ConsoleApplication1.LdapServiceRef.LdapService.ldapAuth(ConsoleApplication1.LdapServiceRef.ldapAuthRequest request) {
            return base.Channel.ldapAuth(request);
        }
        
        public string ldapAuth(string Application, string IdType, string Id, string Password) {
            ConsoleApplication1.LdapServiceRef.ldapAuthRequest inValue = new ConsoleApplication1.LdapServiceRef.ldapAuthRequest();
            inValue.Application = Application;
            inValue.IdType = IdType;
            inValue.Id = Id;
            inValue.Password = Password;
            ConsoleApplication1.LdapServiceRef.ldapAuthResponse retVal = ((ConsoleApplication1.LdapServiceRef.LdapService)(this)).ldapAuth(inValue);
            return retVal.LdapMessage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.LdapServiceRef.ldapAuthResponse> ConsoleApplication1.LdapServiceRef.LdapService.ldapAuthAsync(ConsoleApplication1.LdapServiceRef.ldapAuthRequest request) {
            return base.Channel.ldapAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.LdapServiceRef.ldapAuthResponse> ldapAuthAsync(string Application, string IdType, string Id, string Password) {
            ConsoleApplication1.LdapServiceRef.ldapAuthRequest inValue = new ConsoleApplication1.LdapServiceRef.ldapAuthRequest();
            inValue.Application = Application;
            inValue.IdType = IdType;
            inValue.Id = Id;
            inValue.Password = Password;
            return ((ConsoleApplication1.LdapServiceRef.LdapService)(this)).ldapAuthAsync(inValue);
        }
    }
}
