//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ATSpcWcssSpcActivity {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/asi/", ConfigurationName="ATSpcWcssSpcActivity.WCSS_spcActivity")]
    public interface WCSS_spcActivity {
        
        // CODEGEN: Generating message contract since the operation WCSSActivityInsertOrUpdate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/asi/:WCSSActivityInsertOrUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateResponse WCSSActivityInsertOrUpdate(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/asi/:WCSSActivityInsertOrUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateResponse> WCSSActivityInsertOrUpdateAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation WCSSActivityQueryByExample is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/asi/:WCSSActivityQueryByExample", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleResponse WCSSActivityQueryByExample(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/asi/:WCSSActivityQueryByExample", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleResponse> WCSSActivityQueryByExampleAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest request);
        
        // CODEGEN: Generating message contract since the operation WCSSActivityQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/asi/:WCSSActivityQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryResponse WCSSActivityQuery(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/asi/:WCSSActivityQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryResponse> WCSSActivityQueryAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/asi/")]
    public partial class WCSSActivityInsertOrUpdate_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Action[] listOfAtWcssActionInterfaceInternalField;
        
        private string statusObjectField;
        
        private string sourceSystemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Action[] ListOfAtWcssActionInterfaceInternal {
            get {
                return this.listOfAtWcssActionInterfaceInternalField;
            }
            set {
                this.listOfAtWcssActionInterfaceInternalField = value;
                this.RaisePropertyChanged("ListOfAtWcssActionInterfaceInternal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusObject {
            get {
                return this.statusObjectField;
            }
            set {
                this.statusObjectField = value;
                this.RaisePropertyChanged("StatusObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
                this.RaisePropertyChanged("SourceSystem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal")]
    public partial class Action : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string aTAccessoriesReceivedField;
        
        private string aTAccessoriesShippedField;
        
        private string aTActualReceiveDateField;
        
        private string aTBillingTypeField;
        
        private string aTConditionReceivedField;
        
        private string aTFreightCarrierField;
        
        private string aTFreightCarrierShippingField;
        
        private string aTFreightTrackingNumberField;
        
        private string aTFreightTrackingNumberShippingField;
        
        private string aTNumberOfPackagesField;
        
        private string aTOrderIdField;
        
        private string aTOriginalPackagingUsedField;
        
        private string aTPackagingField;
        
        private string aTServiceNoteNumberField;
        
        private string aTShipDateField;
        
        private string aTWeightField;
        
        private string activityIdField;
        
        private string activityUIDField;
        
        private string commentField;
        
        private string descriptionField;
        
        private string doneField;
        
        private string orderItemIdField;
        
        private string ownerLastNameField;
        
        private string primaryOwnerIdField;
        
        private string sRNumberField;
        
        private string shortCommentField;
        
        private string startedField;
        
        private string statusField;
        
        private string templateFlagField;
        
        private string typeField;
        
        private Action_Employee[] listOfAction_EmployeeField;
        
        private AtTimesheetDailyHours[] listOfAtTimesheetDailyHoursField;
        
        private FsActivityRecommendedPartsTools[] listOfFsActivityRecommendedPartsToolsField;
        
        private string operationField;
        
        private string searchspecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ATAccessoriesReceived {
            get {
                return this.aTAccessoriesReceivedField;
            }
            set {
                this.aTAccessoriesReceivedField = value;
                this.RaisePropertyChanged("ATAccessoriesReceived");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ATAccessoriesShipped {
            get {
                return this.aTAccessoriesShippedField;
            }
            set {
                this.aTAccessoriesShippedField = value;
                this.RaisePropertyChanged("ATAccessoriesShipped");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ATActualReceiveDate {
            get {
                return this.aTActualReceiveDateField;
            }
            set {
                this.aTActualReceiveDateField = value;
                this.RaisePropertyChanged("ATActualReceiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ATBillingType {
            get {
                return this.aTBillingTypeField;
            }
            set {
                this.aTBillingTypeField = value;
                this.RaisePropertyChanged("ATBillingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ATConditionReceived {
            get {
                return this.aTConditionReceivedField;
            }
            set {
                this.aTConditionReceivedField = value;
                this.RaisePropertyChanged("ATConditionReceived");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ATFreightCarrier {
            get {
                return this.aTFreightCarrierField;
            }
            set {
                this.aTFreightCarrierField = value;
                this.RaisePropertyChanged("ATFreightCarrier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ATFreightCarrierShipping {
            get {
                return this.aTFreightCarrierShippingField;
            }
            set {
                this.aTFreightCarrierShippingField = value;
                this.RaisePropertyChanged("ATFreightCarrierShipping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ATFreightTrackingNumber {
            get {
                return this.aTFreightTrackingNumberField;
            }
            set {
                this.aTFreightTrackingNumberField = value;
                this.RaisePropertyChanged("ATFreightTrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ATFreightTrackingNumberShipping {
            get {
                return this.aTFreightTrackingNumberShippingField;
            }
            set {
                this.aTFreightTrackingNumberShippingField = value;
                this.RaisePropertyChanged("ATFreightTrackingNumberShipping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ATNumberOfPackages {
            get {
                return this.aTNumberOfPackagesField;
            }
            set {
                this.aTNumberOfPackagesField = value;
                this.RaisePropertyChanged("ATNumberOfPackages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ATOrderId {
            get {
                return this.aTOrderIdField;
            }
            set {
                this.aTOrderIdField = value;
                this.RaisePropertyChanged("ATOrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ATOriginalPackagingUsed {
            get {
                return this.aTOriginalPackagingUsedField;
            }
            set {
                this.aTOriginalPackagingUsedField = value;
                this.RaisePropertyChanged("ATOriginalPackagingUsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ATPackaging {
            get {
                return this.aTPackagingField;
            }
            set {
                this.aTPackagingField = value;
                this.RaisePropertyChanged("ATPackaging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ATServiceNoteNumber {
            get {
                return this.aTServiceNoteNumberField;
            }
            set {
                this.aTServiceNoteNumberField = value;
                this.RaisePropertyChanged("ATServiceNoteNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ATShipDate {
            get {
                return this.aTShipDateField;
            }
            set {
                this.aTShipDateField = value;
                this.RaisePropertyChanged("ATShipDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ATWeight {
            get {
                return this.aTWeightField;
            }
            set {
                this.aTWeightField = value;
                this.RaisePropertyChanged("ATWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ActivityId {
            get {
                return this.activityIdField;
            }
            set {
                this.activityIdField = value;
                this.RaisePropertyChanged("ActivityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ActivityUID {
            get {
                return this.activityUIDField;
            }
            set {
                this.activityUIDField = value;
                this.RaisePropertyChanged("ActivityUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Done {
            get {
                return this.doneField;
            }
            set {
                this.doneField = value;
                this.RaisePropertyChanged("Done");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OrderItemId {
            get {
                return this.orderItemIdField;
            }
            set {
                this.orderItemIdField = value;
                this.RaisePropertyChanged("OrderItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string OwnerLastName {
            get {
                return this.ownerLastNameField;
            }
            set {
                this.ownerLastNameField = value;
                this.RaisePropertyChanged("OwnerLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string PrimaryOwnerId {
            get {
                return this.primaryOwnerIdField;
            }
            set {
                this.primaryOwnerIdField = value;
                this.RaisePropertyChanged("PrimaryOwnerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ShortComment {
            get {
                return this.shortCommentField;
            }
            set {
                this.shortCommentField = value;
                this.RaisePropertyChanged("ShortComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Started {
            get {
                return this.startedField;
            }
            set {
                this.startedField = value;
                this.RaisePropertyChanged("Started");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string TemplateFlag {
            get {
                return this.templateFlagField;
            }
            set {
                this.templateFlagField = value;
                this.RaisePropertyChanged("TemplateFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=31)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Action_Employee[] ListOfAction_Employee {
            get {
                return this.listOfAction_EmployeeField;
            }
            set {
                this.listOfAction_EmployeeField = value;
                this.RaisePropertyChanged("ListOfAction_Employee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=32)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AtTimesheetDailyHours[] ListOfAtTimesheetDailyHours {
            get {
                return this.listOfAtTimesheetDailyHoursField;
            }
            set {
                this.listOfAtTimesheetDailyHoursField = value;
                this.RaisePropertyChanged("ListOfAtTimesheetDailyHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=33)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FsActivityRecommendedPartsTools[] ListOfFsActivityRecommendedPartsTools {
            get {
                return this.listOfFsActivityRecommendedPartsToolsField;
            }
            set {
                this.listOfFsActivityRecommendedPartsToolsField = value;
                this.RaisePropertyChanged("ListOfFsActivityRecommendedPartsTools");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string searchspec {
            get {
                return this.searchspecField;
            }
            set {
                this.searchspecField = value;
                this.RaisePropertyChanged("searchspec");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal")]
    public partial class Action_Employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aTEmployeeField;
        
        private string employeeFirstNameField;
        
        private string employeeLastNameField;
        
        private string ownedByField;
        
        private string ownedByIdField;
        
        private string isPrimaryMVGField;
        
        private string operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ATEmployee {
            get {
                return this.aTEmployeeField;
            }
            set {
                this.aTEmployeeField = value;
                this.RaisePropertyChanged("ATEmployee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmployeeFirstName {
            get {
                return this.employeeFirstNameField;
            }
            set {
                this.employeeFirstNameField = value;
                this.RaisePropertyChanged("EmployeeFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmployeeLastName {
            get {
                return this.employeeLastNameField;
            }
            set {
                this.employeeLastNameField = value;
                this.RaisePropertyChanged("EmployeeLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OwnedBy {
            get {
                return this.ownedByField;
            }
            set {
                this.ownedByField = value;
                this.RaisePropertyChanged("OwnedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OwnedById {
            get {
                return this.ownedByIdField;
            }
            set {
                this.ownedByIdField = value;
                this.RaisePropertyChanged("OwnedById");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsPrimaryMVG {
            get {
                return this.isPrimaryMVGField;
            }
            set {
                this.isPrimaryMVGField = value;
                this.RaisePropertyChanged("IsPrimaryMVG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal")]
    public partial class FSActivityRecommendedPartsTools_FSActivityOrderItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aTOrderQtyField;
        
        private string orderIdField;
        
        private string orderLineItemStatusField;
        
        private string orderNumberField;
        
        private string isPrimaryMVGField;
        
        private string operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ATOrderQty {
            get {
                return this.aTOrderQtyField;
            }
            set {
                this.aTOrderQtyField = value;
                this.RaisePropertyChanged("ATOrderQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderLineItemStatus {
            get {
                return this.orderLineItemStatusField;
            }
            set {
                this.orderLineItemStatusField = value;
                this.RaisePropertyChanged("OrderLineItemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsPrimaryMVG {
            get {
                return this.isPrimaryMVGField;
            }
            set {
                this.isPrimaryMVGField = value;
                this.RaisePropertyChanged("IsPrimaryMVG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal")]
    public partial class FsActivityRecommendedPartsTools : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string aTIncludeinBillableTotalField;
        
        private string aTLocationField;
        
        private string aTNewSerialNumberField;
        
        private string aTOldSerialNumberField;
        
        private string aTOrderIdField;
        
        private string aTPartsFailCodeField;
        
        private string aTPartsUsedCodeField;
        
        private string aTRefDesignatorField;
        
        private string aTReturnToField;
        
        private string activityDescriptionField;
        
        private string activityIdField;
        
        private string activityTypeField;
        
        private string orderNumberforCEField;
        
        private string partField;
        
        private string primaryOrderItemIdField;
        
        private string productIdField;
        
        private string productNameField;
        
        private string recommendedQuantityField;
        
        private string relationTypeField;
        
        private string returnDefectiveField;
        
        private string aTLineFailureCommentField;
        
        private FSActivityRecommendedPartsTools_FSActivityOrderItem[] listOfFSActivityRecommendedPartsTools_FSActivityOrderItemField;
        
        private string operationField;
        
        private string searchspecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ATIncludeinBillableTotal {
            get {
                return this.aTIncludeinBillableTotalField;
            }
            set {
                this.aTIncludeinBillableTotalField = value;
                this.RaisePropertyChanged("ATIncludeinBillableTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ATLocation {
            get {
                return this.aTLocationField;
            }
            set {
                this.aTLocationField = value;
                this.RaisePropertyChanged("ATLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ATNewSerialNumber {
            get {
                return this.aTNewSerialNumberField;
            }
            set {
                this.aTNewSerialNumberField = value;
                this.RaisePropertyChanged("ATNewSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ATOldSerialNumber {
            get {
                return this.aTOldSerialNumberField;
            }
            set {
                this.aTOldSerialNumberField = value;
                this.RaisePropertyChanged("ATOldSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ATOrderId {
            get {
                return this.aTOrderIdField;
            }
            set {
                this.aTOrderIdField = value;
                this.RaisePropertyChanged("ATOrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ATPartsFailCode {
            get {
                return this.aTPartsFailCodeField;
            }
            set {
                this.aTPartsFailCodeField = value;
                this.RaisePropertyChanged("ATPartsFailCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ATPartsUsedCode {
            get {
                return this.aTPartsUsedCodeField;
            }
            set {
                this.aTPartsUsedCodeField = value;
                this.RaisePropertyChanged("ATPartsUsedCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATRef.Designator", Order=8)]
        public string ATRefDesignator {
            get {
                return this.aTRefDesignatorField;
            }
            set {
                this.aTRefDesignatorField = value;
                this.RaisePropertyChanged("ATRefDesignator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ATReturnTo {
            get {
                return this.aTReturnToField;
            }
            set {
                this.aTReturnToField = value;
                this.RaisePropertyChanged("ATReturnTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ActivityDescription {
            get {
                return this.activityDescriptionField;
            }
            set {
                this.activityDescriptionField = value;
                this.RaisePropertyChanged("ActivityDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ActivityId {
            get {
                return this.activityIdField;
            }
            set {
                this.activityIdField = value;
                this.RaisePropertyChanged("ActivityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ActivityType {
            get {
                return this.activityTypeField;
            }
            set {
                this.activityTypeField = value;
                this.RaisePropertyChanged("ActivityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string OrderNumberforCE {
            get {
                return this.orderNumberforCEField;
            }
            set {
                this.orderNumberforCEField = value;
                this.RaisePropertyChanged("OrderNumberforCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
                this.RaisePropertyChanged("Part");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PrimaryOrderItemId {
            get {
                return this.primaryOrderItemIdField;
            }
            set {
                this.primaryOrderItemIdField = value;
                this.RaisePropertyChanged("PrimaryOrderItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string RecommendedQuantity {
            get {
                return this.recommendedQuantityField;
            }
            set {
                this.recommendedQuantityField = value;
                this.RaisePropertyChanged("RecommendedQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string RelationType {
            get {
                return this.relationTypeField;
            }
            set {
                this.relationTypeField = value;
                this.RaisePropertyChanged("RelationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ReturnDefective {
            get {
                return this.returnDefectiveField;
            }
            set {
                this.returnDefectiveField = value;
                this.RaisePropertyChanged("ReturnDefective");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ATLineFailureComment {
            get {
                return this.aTLineFailureCommentField;
            }
            set {
                this.aTLineFailureCommentField = value;
                this.RaisePropertyChanged("ATLineFailureComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=22)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FSActivityRecommendedPartsTools_FSActivityOrderItem[] ListOfFSActivityRecommendedPartsTools_FSActivityOrderItem {
            get {
                return this.listOfFSActivityRecommendedPartsTools_FSActivityOrderItemField;
            }
            set {
                this.listOfFSActivityRecommendedPartsTools_FSActivityOrderItemField = value;
                this.RaisePropertyChanged("ListOfFSActivityRecommendedPartsTools_FSActivityOrderItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string searchspec {
            get {
                return this.searchspecField;
            }
            set {
                this.searchspecField = value;
                this.RaisePropertyChanged("searchspec");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal")]
    public partial class AtTimesheetDailyHours : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string createdField;
        
        private string aTElapsedTimeField;
        
        private string aTEstimatedTimeField;
        
        private string aTLaborItemNumberField;
        
        private string aTOrderIdField;
        
        private string aTTypeField;
        
        private string activityIdField;
        
        private string itemDateField;
        
        private string ownerLoginField;
        
        private string reportedTimeField;
        
        private string timeSheetItemNumField;
        
        private string operationField;
        
        private string searchspecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ATElapsedTime {
            get {
                return this.aTElapsedTimeField;
            }
            set {
                this.aTElapsedTimeField = value;
                this.RaisePropertyChanged("ATElapsedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ATEstimatedTime {
            get {
                return this.aTEstimatedTimeField;
            }
            set {
                this.aTEstimatedTimeField = value;
                this.RaisePropertyChanged("ATEstimatedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ATLaborItemNumber {
            get {
                return this.aTLaborItemNumberField;
            }
            set {
                this.aTLaborItemNumberField = value;
                this.RaisePropertyChanged("ATLaborItemNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ATOrderId {
            get {
                return this.aTOrderIdField;
            }
            set {
                this.aTOrderIdField = value;
                this.RaisePropertyChanged("ATOrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ATType {
            get {
                return this.aTTypeField;
            }
            set {
                this.aTTypeField = value;
                this.RaisePropertyChanged("ATType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ActivityId {
            get {
                return this.activityIdField;
            }
            set {
                this.activityIdField = value;
                this.RaisePropertyChanged("ActivityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ItemDate {
            get {
                return this.itemDateField;
            }
            set {
                this.itemDateField = value;
                this.RaisePropertyChanged("ItemDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OwnerLogin {
            get {
                return this.ownerLoginField;
            }
            set {
                this.ownerLoginField = value;
                this.RaisePropertyChanged("OwnerLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ReportedTime {
            get {
                return this.reportedTimeField;
            }
            set {
                this.reportedTimeField = value;
                this.RaisePropertyChanged("ReportedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TimeSheetItemNum {
            get {
                return this.timeSheetItemNumField;
            }
            set {
                this.timeSheetItemNumField = value;
                this.RaisePropertyChanged("TimeSheetItemNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string searchspec {
            get {
                return this.searchspecField;
            }
            set {
                this.searchspecField = value;
                this.RaisePropertyChanged("searchspec");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/asi/")]
    public partial class WCSSActivityInsertOrUpdate_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Action[] listOfAtWcssActionInterfaceInternalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Action[] ListOfAtWcssActionInterfaceInternal {
            get {
                return this.listOfAtWcssActionInterfaceInternalField;
            }
            set {
                this.listOfAtWcssActionInterfaceInternalField = value;
                this.RaisePropertyChanged("ListOfAtWcssActionInterfaceInternal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WCSSActivityInsertOrUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/asi/", Order=0)]
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdate_Input WCSSActivityInsertOrUpdate_Input;
        
        public WCSSActivityInsertOrUpdateRequest() {
        }
        
        public WCSSActivityInsertOrUpdateRequest(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdate_Input WCSSActivityInsertOrUpdate_Input) {
            this.WCSSActivityInsertOrUpdate_Input = WCSSActivityInsertOrUpdate_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WCSSActivityInsertOrUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/asi/", Order=0)]
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdate_Output WCSSActivityInsertOrUpdate_Output;
        
        public WCSSActivityInsertOrUpdateResponse() {
        }
        
        public WCSSActivityInsertOrUpdateResponse(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdate_Output WCSSActivityInsertOrUpdate_Output) {
            this.WCSSActivityInsertOrUpdate_Output = WCSSActivityInsertOrUpdate_Output;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/asi/")]
    public partial class WCSSActivityQueryByExample_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Action[] listOfAtWcssActionInterfaceInternalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Action[] ListOfAtWcssActionInterfaceInternal {
            get {
                return this.listOfAtWcssActionInterfaceInternalField;
            }
            set {
                this.listOfAtWcssActionInterfaceInternalField = value;
                this.RaisePropertyChanged("ListOfAtWcssActionInterfaceInternal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/asi/")]
    public partial class WCSSActivityQueryByExample_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Action[] listOfAtWcssActionInterfaceInternalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Action[] ListOfAtWcssActionInterfaceInternal {
            get {
                return this.listOfAtWcssActionInterfaceInternalField;
            }
            set {
                this.listOfAtWcssActionInterfaceInternalField = value;
                this.RaisePropertyChanged("ListOfAtWcssActionInterfaceInternal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WCSSActivityQueryByExampleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/asi/", Order=0)]
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExample_Input WCSSActivityQueryByExample_Input;
        
        public WCSSActivityQueryByExampleRequest() {
        }
        
        public WCSSActivityQueryByExampleRequest(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExample_Input WCSSActivityQueryByExample_Input) {
            this.WCSSActivityQueryByExample_Input = WCSSActivityQueryByExample_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WCSSActivityQueryByExampleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/asi/", Order=0)]
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExample_Output WCSSActivityQueryByExample_Output;
        
        public WCSSActivityQueryByExampleResponse() {
        }
        
        public WCSSActivityQueryByExampleResponse(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExample_Output WCSSActivityQueryByExample_Output) {
            this.WCSSActivityQueryByExample_Output = WCSSActivityQueryByExample_Output;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/asi/")]
    public partial class WCSSActivityQuery_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string primaryRowIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PrimaryRowId {
            get {
                return this.primaryRowIdField;
            }
            set {
                this.primaryRowIdField = value;
                this.RaisePropertyChanged("PrimaryRowId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/asi/")]
    public partial class WCSSActivityQuery_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Action[] listOfAtWcssActionInterfaceInternalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/AT%20WCSS%20Action%20Interface%20Internal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Action[] ListOfAtWcssActionInterfaceInternal {
            get {
                return this.listOfAtWcssActionInterfaceInternalField;
            }
            set {
                this.listOfAtWcssActionInterfaceInternalField = value;
                this.RaisePropertyChanged("ListOfAtWcssActionInterfaceInternal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WCSSActivityQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/asi/", Order=0)]
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQuery_Input WCSSActivityQuery_Input;
        
        public WCSSActivityQueryRequest() {
        }
        
        public WCSSActivityQueryRequest(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQuery_Input WCSSActivityQuery_Input) {
            this.WCSSActivityQuery_Input = WCSSActivityQuery_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WCSSActivityQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/asi/", Order=0)]
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQuery_Output WCSSActivityQuery_Output;
        
        public WCSSActivityQueryResponse() {
        }
        
        public WCSSActivityQueryResponse(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQuery_Output WCSSActivityQuery_Output) {
            this.WCSSActivityQuery_Output = WCSSActivityQuery_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCSS_spcActivityChannel : ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCSS_spcActivityClient : System.ServiceModel.ClientBase<ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity>, ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity {
        
        public WCSS_spcActivityClient() {
        }
        
        public WCSS_spcActivityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCSS_spcActivityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCSS_spcActivityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCSS_spcActivityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateResponse ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity.WCSSActivityInsertOrUpdate(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest request) {
            return base.Channel.WCSSActivityInsertOrUpdate(request);
        }
        
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdate_Output WCSSActivityInsertOrUpdate(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdate_Input WCSSActivityInsertOrUpdate_Input) {
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest inValue = new ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest();
            inValue.WCSSActivityInsertOrUpdate_Input = WCSSActivityInsertOrUpdate_Input;
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateResponse retVal = ((ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity)(this)).WCSSActivityInsertOrUpdate(inValue);
            return retVal.WCSSActivityInsertOrUpdate_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateResponse> ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity.WCSSActivityInsertOrUpdateAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest request) {
            return base.Channel.WCSSActivityInsertOrUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateResponse> WCSSActivityInsertOrUpdateAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdate_Input WCSSActivityInsertOrUpdate_Input) {
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest inValue = new ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityInsertOrUpdateRequest();
            inValue.WCSSActivityInsertOrUpdate_Input = WCSSActivityInsertOrUpdate_Input;
            return ((ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity)(this)).WCSSActivityInsertOrUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleResponse ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity.WCSSActivityQueryByExample(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest request) {
            return base.Channel.WCSSActivityQueryByExample(request);
        }
        
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExample_Output WCSSActivityQueryByExample(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExample_Input WCSSActivityQueryByExample_Input) {
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest inValue = new ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest();
            inValue.WCSSActivityQueryByExample_Input = WCSSActivityQueryByExample_Input;
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleResponse retVal = ((ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity)(this)).WCSSActivityQueryByExample(inValue);
            return retVal.WCSSActivityQueryByExample_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleResponse> ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity.WCSSActivityQueryByExampleAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest request) {
            return base.Channel.WCSSActivityQueryByExampleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleResponse> WCSSActivityQueryByExampleAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExample_Input WCSSActivityQueryByExample_Input) {
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest inValue = new ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryByExampleRequest();
            inValue.WCSSActivityQueryByExample_Input = WCSSActivityQueryByExample_Input;
            return ((ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity)(this)).WCSSActivityQueryByExampleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryResponse ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity.WCSSActivityQuery(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest request) {
            return base.Channel.WCSSActivityQuery(request);
        }
        
        public ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQuery_Output WCSSActivityQuery(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQuery_Input WCSSActivityQuery_Input) {
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest inValue = new ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest();
            inValue.WCSSActivityQuery_Input = WCSSActivityQuery_Input;
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryResponse retVal = ((ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity)(this)).WCSSActivityQuery(inValue);
            return retVal.WCSSActivityQuery_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryResponse> ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity.WCSSActivityQueryAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest request) {
            return base.Channel.WCSSActivityQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryResponse> WCSSActivityQueryAsync(ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQuery_Input WCSSActivityQuery_Input) {
            ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest inValue = new ConsoleApplication1.ATSpcWcssSpcActivity.WCSSActivityQueryRequest();
            inValue.WCSSActivityQuery_Input = WCSSActivityQuery_Input;
            return ((ConsoleApplication1.ATSpcWcssSpcActivity.WCSS_spcActivity)(this)).WCSSActivityQueryAsync(inValue);
        }
    }
}
