//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="LdapService", Namespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth")]
public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ldapAuthOperationCompleted;
    
    /// <remarks/>
    public Service() {
        this.Url = "https://lcossdo4.cos.is.keysight.com/cgi-bin/soap/LdapAuth.cgi";
    }
    
    /// <remarks/>
    public event ldapAuthCompletedEventHandler ldapAuthCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wcss.keysight.com/EnterpriseBroker/LdapAuth#ldapAuth", RequestNamespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", ResponseElementName="ldapMessageResponse", ResponseNamespace="http://wcss.keysight.com/EnterpriseBroker/LdapAuth", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("LdapMessage")]
    public string ldapAuth(string Application, string IdType, string Id, string Password) {
        object[] results = this.Invoke("ldapAuth", new object[] {
                    Application,
                    IdType,
                    Id,
                    Password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginldapAuth(string Application, string IdType, string Id, string Password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ldapAuth", new object[] {
                    Application,
                    IdType,
                    Id,
                    Password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndldapAuth(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ldapAuthAsync(string Application, string IdType, string Id, string Password) {
        this.ldapAuthAsync(Application, IdType, Id, Password, null);
    }
    
    /// <remarks/>
    public void ldapAuthAsync(string Application, string IdType, string Id, string Password, object userState) {
        if ((this.ldapAuthOperationCompleted == null)) {
            this.ldapAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnldapAuthOperationCompleted);
        }
        this.InvokeAsync("ldapAuth", new object[] {
                    Application,
                    IdType,
                    Id,
                    Password}, this.ldapAuthOperationCompleted, userState);
    }
    
    private void OnldapAuthOperationCompleted(object arg) {
        if ((this.ldapAuthCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ldapAuthCompleted(this, new ldapAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void ldapAuthCompletedEventHandler(object sender, ldapAuthCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ldapAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ldapAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
