//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ConsoleApplication1
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ServiceOrder
    {

        private ServiceOrderHeader headerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceOrderHeader", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceOrderHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ServiceOrderHeader
    {

        private string wDBField;

        private string mailToField;

        private string serviceOrderNumberField;

        private string codePageField;

        private string oCPPVersionField;

        private ServiceOrderAccount accountField;

        private ListOfLineItems listOfLineItemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WDB
        {
            get
            {
                return this.wDBField;
            }
            set
            {
                this.wDBField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MailTo
        {
            get
            {
                return this.mailToField;
            }
            set
            {
                this.mailToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceOrderNumber
        {
            get
            {
                return this.serviceOrderNumberField;
            }
            set
            {
                this.serviceOrderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodePage
        {
            get
            {
                return this.codePageField;
            }
            set
            {
                this.codePageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OCPPVersion
        {
            get
            {
                return this.oCPPVersionField;
            }
            set
            {
                this.oCPPVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceOrderAccount Account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ListOfLineItems ListOfLineItems
        {
            get
            {
                return this.listOfLineItemsField;
            }
            set
            {
                this.listOfLineItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ServiceOrderAccount
    {

        private string customerNumberField;

        private string customerNameField;

        private string cFDLanguageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CFDLanguage
        {
            get
            {
                return this.cFDLanguageField;
            }
            set
            {
                this.cFDLanguageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ListOfLineItems
    {

        private ServiceOrderLineItem[] lineItemField;

        private string totalLaborHourField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceOrderLineItem[] LineItem
        {
            get
            {
                return this.lineItemField;
            }
            set
            {
                this.lineItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TotalLaborHour
        {
            get
            {
                return this.totalLaborHourField;
            }
            set
            {
                this.totalLaborHourField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ServiceOrderLineItem
    {

        private string adjustmentPerformedField;

        private string agilentModelField;

        private string assetCalibrationIntervalField;

        private string billingTypeField;

        private string calDateField;

        private string customerAssetTagField;

        private string employeeNumberField;

        private string lineItemStatusField;

        private string lineNumberField;

        private string mUEmployeeNumberField;

        private string postSafetyTestField;

        private string preSafetyTestField;

        private string receiveDateField;

        private string reportedTimeField;

        private string serialNumberField;

        private string technicianCESymptomsField;

        private string serviceActivityCodeField;

        private string applicableStandardField;

        private string locationCodeField;

        private string accountAuthorizationNumberField;

        private string internalAssetField;

        private string assetDepartmentField;

        private string assetUserField;

        private string mfrCodeField;

        private string mfrModelField;

        private string installedOptionsField;

        private string installedDescriptionField;

        private string calDueOnCertificateField;

        private string calDueDateField;

        private string calIntervalSourceField;

        private string reasonForCalField;

        private string authorizingEmployeeNumberField;

        private string commentsField;

        private string tetheredField;

        private CalibrationResults calibrationResultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AdjustmentPerformed
        {
            get
            {
                return this.adjustmentPerformedField;
            }
            set
            {
                this.adjustmentPerformedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AgilentModel
        {
            get
            {
                return this.agilentModelField;
            }
            set
            {
                this.agilentModelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssetCalibrationInterval
        {
            get
            {
                return this.assetCalibrationIntervalField;
            }
            set
            {
                this.assetCalibrationIntervalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillingType
        {
            get
            {
                return this.billingTypeField;
            }
            set
            {
                this.billingTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CalDate
        {
            get
            {
                return this.calDateField;
            }
            set
            {
                this.calDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerAssetTag
        {
            get
            {
                return this.customerAssetTagField;
            }
            set
            {
                this.customerAssetTagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmployeeNumber
        {
            get
            {
                return this.employeeNumberField;
            }
            set
            {
                this.employeeNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineItemStatus
        {
            get
            {
                return this.lineItemStatusField;
            }
            set
            {
                this.lineItemStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MUEmployeeNumber
        {
            get
            {
                return this.mUEmployeeNumberField;
            }
            set
            {
                this.mUEmployeeNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostSafetyTest
        {
            get
            {
                return this.postSafetyTestField;
            }
            set
            {
                this.postSafetyTestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PreSafetyTest
        {
            get
            {
                return this.preSafetyTestField;
            }
            set
            {
                this.preSafetyTestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiveDate
        {
            get
            {
                return this.receiveDateField;
            }
            set
            {
                this.receiveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReportedTime
        {
            get
            {
                return this.reportedTimeField;
            }
            set
            {
                this.reportedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TechnicianCESymptoms
        {
            get
            {
                return this.technicianCESymptomsField;
            }
            set
            {
                this.technicianCESymptomsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceActivityCode
        {
            get
            {
                return this.serviceActivityCodeField;
            }
            set
            {
                this.serviceActivityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApplicableStandard
        {
            get
            {
                return this.applicableStandardField;
            }
            set
            {
                this.applicableStandardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccountAuthorizationNumber
        {
            get
            {
                return this.accountAuthorizationNumberField;
            }
            set
            {
                this.accountAuthorizationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalAsset
        {
            get
            {
                return this.internalAssetField;
            }
            set
            {
                this.internalAssetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssetDepartment
        {
            get
            {
                return this.assetDepartmentField;
            }
            set
            {
                this.assetDepartmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssetUser
        {
            get
            {
                return this.assetUserField;
            }
            set
            {
                this.assetUserField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MfrCode
        {
            get
            {
                return this.mfrCodeField;
            }
            set
            {
                this.mfrCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MfrModel
        {
            get
            {
                return this.mfrModelField;
            }
            set
            {
                this.mfrModelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InstalledOptions
        {
            get
            {
                return this.installedOptionsField;
            }
            set
            {
                this.installedOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InstalledDescription
        {
            get
            {
                return this.installedDescriptionField;
            }
            set
            {
                this.installedDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CalDueOnCertificate
        {
            get
            {
                return this.calDueOnCertificateField;
            }
            set
            {
                this.calDueOnCertificateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CalDueDate
        {
            get
            {
                return this.calDueDateField;
            }
            set
            {
                this.calDueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CalIntervalSource
        {
            get
            {
                return this.calIntervalSourceField;
            }
            set
            {
                this.calIntervalSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReasonForCal
        {
            get
            {
                return this.reasonForCalField;
            }
            set
            {
                this.reasonForCalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AuthorizingEmployeeNumber
        {
            get
            {
                return this.authorizingEmployeeNumberField;
            }
            set
            {
                this.authorizingEmployeeNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tethered
        {
            get
            {
                return this.tetheredField;
            }
            set
            {
                this.tetheredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CalibrationResults CalibrationResults
        {
            get
            {
                return this.calibrationResultsField;
            }
            set
            {
                this.calibrationResultsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CalibrationResults
    {

        private string procedureUsedField;

        private string accProcedureUsedField;

        private string asReceiveConditionField;

        private string correctiveActionField;

        private string asCompletedConditionField;

        private string sealIntactFlagField;

        private string temperatureRangeField;

        private string humidityRangeField;

        private string lineMainsFrequencyField;

        private CalibrationStandard[] standardsUsedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcedureUsed
        {
            get
            {
                return this.procedureUsedField;
            }
            set
            {
                this.procedureUsedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccProcedureUsed
        {
            get
            {
                return this.accProcedureUsedField;
            }
            set
            {
                this.accProcedureUsedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AsReceiveCondition
        {
            get
            {
                return this.asReceiveConditionField;
            }
            set
            {
                this.asReceiveConditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CorrectiveAction
        {
            get
            {
                return this.correctiveActionField;
            }
            set
            {
                this.correctiveActionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AsCompletedCondition
        {
            get
            {
                return this.asCompletedConditionField;
            }
            set
            {
                this.asCompletedConditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SealIntactFlag
        {
            get
            {
                return this.sealIntactFlagField;
            }
            set
            {
                this.sealIntactFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TemperatureRange
        {
            get
            {
                return this.temperatureRangeField;
            }
            set
            {
                this.temperatureRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HumidityRange
        {
            get
            {
                return this.humidityRangeField;
            }
            set
            {
                this.humidityRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineMainsFrequency
        {
            get
            {
                return this.lineMainsFrequencyField;
            }
            set
            {
                this.lineMainsFrequencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CalibrationStandard", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public CalibrationStandard[] StandardsUsed
        {
            get
            {
                return this.standardsUsedField;
            }
            set
            {
                this.standardsUsedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CalibrationStandard
    {

        private string agilentModelField;

        private string assetIDField;

        private string calDueDateField;

        private string installedDescriptionField;

        private string serialNumberField;

        private string serviceOrderNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AgilentModel
        {
            get
            {
                return this.agilentModelField;
            }
            set
            {
                this.agilentModelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssetID
        {
            get
            {
                return this.assetIDField;
            }
            set
            {
                this.assetIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CalDueDate
        {
            get
            {
                return this.calDueDateField;
            }
            set
            {
                this.calDueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InstalledDescription
        {
            get
            {
                return this.installedDescriptionField;
            }
            set
            {
                this.installedDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceOrderNumber
        {
            get
            {
                return this.serviceOrderNumberField;
            }
            set
            {
                this.serviceOrderNumberField = value;
            }
        }
    }
}
