//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.TestSoapRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestSoapRef.TestSoapWebSvcSoap")]
    public interface TestSoapWebSvcSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleApplication1.TestSoapRef.HelloWorldResponse HelloWorld(ConsoleApplication1.TestSoapRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.TestSoapRef.HelloWorldResponse> HelloWorldAsync(ConsoleApplication1.TestSoapRef.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name iam from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMethod", ReplyAction="*")]
        ConsoleApplication1.TestSoapRef.TestMethodResponse TestMethod(ConsoleApplication1.TestSoapRef.TestMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.TestSoapRef.TestMethodResponse> TestMethodAsync(ConsoleApplication1.TestSoapRef.TestMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.TestSoapRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApplication1.TestSoapRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.TestSoapRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApplication1.TestSoapRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethod", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.TestSoapRef.TestMethodRequestBody Body;
        
        public TestMethodRequest() {
        }
        
        public TestMethodRequest(ConsoleApplication1.TestSoapRef.TestMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iam;
        
        public TestMethodRequestBody() {
        }
        
        public TestMethodRequestBody(string iam) {
            this.iam = iam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.TestSoapRef.TestMethodResponseBody Body;
        
        public TestMethodResponse() {
        }
        
        public TestMethodResponse(ConsoleApplication1.TestSoapRef.TestMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestMethodResult;
        
        public TestMethodResponseBody() {
        }
        
        public TestMethodResponseBody(string TestMethodResult) {
            this.TestMethodResult = TestMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestSoapWebSvcSoapChannel : ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestSoapWebSvcSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap>, ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap {
        
        public TestSoapWebSvcSoapClient() {
        }
        
        public TestSoapWebSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestSoapWebSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSoapWebSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestSoapWebSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.TestSoapRef.HelloWorldResponse ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap.HelloWorld(ConsoleApplication1.TestSoapRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApplication1.TestSoapRef.HelloWorldRequest inValue = new ConsoleApplication1.TestSoapRef.HelloWorldRequest();
            inValue.Body = new ConsoleApplication1.TestSoapRef.HelloWorldRequestBody();
            ConsoleApplication1.TestSoapRef.HelloWorldResponse retVal = ((ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.TestSoapRef.HelloWorldResponse> ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap.HelloWorldAsync(ConsoleApplication1.TestSoapRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.TestSoapRef.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApplication1.TestSoapRef.HelloWorldRequest inValue = new ConsoleApplication1.TestSoapRef.HelloWorldRequest();
            inValue.Body = new ConsoleApplication1.TestSoapRef.HelloWorldRequestBody();
            return ((ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.TestSoapRef.TestMethodResponse ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap.TestMethod(ConsoleApplication1.TestSoapRef.TestMethodRequest request) {
            return base.Channel.TestMethod(request);
        }
        
        public string TestMethod(string iam) {
            ConsoleApplication1.TestSoapRef.TestMethodRequest inValue = new ConsoleApplication1.TestSoapRef.TestMethodRequest();
            inValue.Body = new ConsoleApplication1.TestSoapRef.TestMethodRequestBody();
            inValue.Body.iam = iam;
            ConsoleApplication1.TestSoapRef.TestMethodResponse retVal = ((ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap)(this)).TestMethod(inValue);
            return retVal.Body.TestMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.TestSoapRef.TestMethodResponse> ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap.TestMethodAsync(ConsoleApplication1.TestSoapRef.TestMethodRequest request) {
            return base.Channel.TestMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.TestSoapRef.TestMethodResponse> TestMethodAsync(string iam) {
            ConsoleApplication1.TestSoapRef.TestMethodRequest inValue = new ConsoleApplication1.TestSoapRef.TestMethodRequest();
            inValue.Body = new ConsoleApplication1.TestSoapRef.TestMethodRequestBody();
            inValue.Body.iam = iam;
            return ((ConsoleApplication1.TestSoapRef.TestSoapWebSvcSoap)(this)).TestMethodAsync(inValue);
        }
    }
}
